name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: arduino/setup-arduino-cli@v1.1.1
      - name: install Arduino cores and libraries
        run: |
          arduino-cli version
          arduino-cli core update-index --additional-urls $ARDUINO_CORE_URI
          arduino-cli core install esp32:esp32 --additional-urls $ARDUINO_CORE_URI
        env:
          ARDUINO_CORE_URI: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install esptool
      - uses: actions/checkout@v2
      - name: check code style
        run: |
          mk/format-code.sh
          [[ $(git status --porcelain | tee >(cat 1>&2) | wc -l) -eq 0 ]]
      - name: link library
        run: |
          mkdir -p $HOME/Arduino/libraries/ODROID-GO
          cd $HOME/Arduino/libraries
          ln -s $GITHUB_WORKSPACE esp32cam
          curl -sfL https://github.com/hardkernel/ODROID-GO/archive/${ODROIDGO_VERSION}.tar.gz | tar -C ODROID-GO -xz --strip-components=1
        env:
          ODROIDGO_VERSION: master
      - name: compile WifiCam example
        run: |
          arduino-cli compile -b esp32:esp32:esp32wrover ./examples/WifiCam
      - name: compile GoDisplay example
        run: |
          arduino-cli compile -b esp32:esp32:odroid_esp32 ./examples/GoDisplay
      - name: build docs
        run: |
          sudo apt-get install doxygen
          docs/build.sh
      - name: deploy docs
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: 7de100ca-e942-419d-af2c-18e6c528b96e
          build-dir: ./docs/html/
        if: ${{ github.repository == 'yoursunny/esp32cam' && github.event_name == 'push' }}
